### ISSUE TITLE
PKGBUILD-generic-jointscript could not manage cases of tools using arguments requiring relative paths

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch-pkgbuilds#17]
Hello, https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-generic-jointscript template could not be able to manage the specific case where a tool inside its code tries to call a resource by a relative path.

This could be seen in the following piece of this template:
```
cat > "$pkgdir/usr/bin/$pkgname" << EOF
#!/bin/sh
cd /usr/share/$pkgname
exec ./$pkgname "\$@"
EOF
```
Let's guess we have a tool that has a `--input` argument or any argument accepting a filepath.

If the PKGBUILD template creates a `pkgname` file in `/usr/bin/` where inside it has `cd /usr/share/$pkgname`, it means that, when the user in its `$HOME` folder tries to run `toolname --input report.pdf` (so, it uses a relative path), due to `cd /usr/share/$pkgname`, the tool will go to search `report.pdf` inside `/usr/share/toolname` instead of `$HOME`.

I think that, for solving this, that piece of PKGBUILD needs only to be written in the following manner:
```
cat > "$pkgdir/usr/bin/$pkgname" << EOF
#!/bin/sh
exec /usr/share/$pkgname/$pkgname "\$@"
EOF
```
I hope my rationale is correct. I dont know if also other templates use the same logic.

Thank you for your work.

**Comment by noraj** [comment]
Yes, but it's also true the other way around when the script call for relative resources in the install dir and the workdir is the user current dir and not the tool install dir.
For some package the `cd` is needed, for others a direct `exec` is preferable. There is no universal perfect template.
