### ISSUE TITLE
Some packages of blackarch get a version number that is too far from upstream

### ISSUE THREAD

**Issue by unknowndevQwQ** [BlackArch/blackarch-pkgbuilds#19]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

There are some problems with setting version numbers for some packages, here is an example of portspoof.

### Steps to reproduce

- `$ pacman -Sl blackarch`
- Count packages with version numbers higher than three digits and consult their PKGBUILD files.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The pkgver function used is not the archwiki recommended way because the prefix r before the commit number is omitted.
from portspoof/0d1n/gdbgui:
```
pkgver() {
  cd $pkgname

  echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
}
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Use examples from the [archwiki](https://wiki.archlinux.org/title/VCS_package_guidelines#Guidelines), like:
```
pkgver() {
  cd "$pkgname"
  ( set -o pipefail
    # cutting off 'v' prefix that presents in the git tag
    git describe --long --abbrev=7 | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'||
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short=7 HEAD)"
  )
}
```

**Comment by noraj** [comment]
Actual template for git packages

https://github.com/BlackArch/blackarch-pkgbuilds/blob/ed1aab7282e0d4143d3dfc62304376a3c946e705/PKGBUILD-generic-git#L20-L24

**Comment by unknowndevQwQ** [comment]
> Actual template for git packages
> 
> https://github.com/BlackArch/blackarch-pkgbuilds/blob/ed1aab7282e0d4143d3dfc62304376a3c946e705/PKGBUILD-generic-git#L20-L24 

The echo line is missing the prefix r, and I highly recommend that there is some way to try to get the version number from git first.

**Comment by noraj** [comment]
> The revision number delimiter ("r" right before REVISION) is important. This delimiter allows to avoid problems in case if upstream decides to make its first release or uses versions with different number of components. E.g. if at revision "455" upstream decides to release version 0.1 then the revision delimiter preserves version monotonicity - 0.1.r456 > r454. Without the delimiter monotonicity fails - 0.1.456 < 454. 
>
> Ref. https://wiki.archlinux.org/title/VCS_package_guidelines#The_pkgver()_function

I'll make a PR for review.

**Comment by unknowndevQwQ** [comment]
@noraj When can we fix this problem? There are many software packages that still have this type of problem.

Missing r prefix: chankro, cook, hercules-payload, lyricpass
Redundant v prefixes: cracken
