### ISSUE TITLE
PKGBUILD-python-PEP517 - Install Python dependencies

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch-pkgbuilds#26]
In [PKGBUILD-python-PEP517](https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-PEP517) the dependencies are not installed automatically by `pip install` command in `package()` unlike [PKGBUILD Python Standalone](https://github.com/BlackArch/blackarch-pkgbuilds/blob/master/PKGBUILD-python-standalone), right?

Should they be specified in `depends`?

**Comment by noraj** [comment]
Yes, with PEP517 PKGBUILD you need to use system dependencies, that's why `pip install` uses `--no-deps` because we won't pull deps from pypi.
