### ISSUE TITLE
Java JAR PKGBUILD template

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch-pkgbuilds#3]
We may need to add one for Java JAR for example like https://github.com/BlackArch/blackarch/blob/master/packages/barmie

**Comment by noraj** [comment]
:heavy_check_mark: https://github.com/BlackArch/blackarch-pkgbuilds/commit/3c9dff6c943d3414152f859115aacdfce9099847

@Edu4rdSHL @noptrix review?

**Comment by Edu4rdSHL** [comment]
LGTM.
